name: bosch-hold-rust

on: [push, pull_request]

jobs:
  lint:
    name: Lint 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cargo fmt
      run: cargo fmt -- --check --color ${{ env.CARGO_TERM_COLOR }}
    - name: cargo clippy
      run: cargo clippy -- -W warnings


  build:
    name: Build 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build
    - name: Build examples
      run: cargo build --examples
    - name: Run Tests
      run: cargo test --all-targets
   